Tasker/urls.py
from django.conf.urls import patterns, include, url


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('login.urls', namespace="Login")),
    url(r'^home/', include('home.urls', namespace="Home")),
    url(r'^registration/$', include('registration.urls', namespace="Registration")),
    url(r'^password/',include('passwordreset.urls', namespace= "PasswordReset")),
    url(r'^tasks/', include('tasks.urls', namespace= "Task")),
    # Examples:
    # url(r'^$', 'Tasker.views.home', name='home'),
    # url(r'^Tasker/', include('Tasker.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

home/urls.py
from django.conf.urls import patterns, url

from home import views
from projects import views as project_views

urlpatterns = patterns('',
    url(r'^user/$', views.user_profile_view, name='user'),
    url(r'^manager/$', views.manager_profile_view, name='manager'),
    url(r'^manager/projects/$', project_views.add_project_view, name='add_project'),
    url(r'^manager/projects/details/$', project_views.project_detail_view, name='project_detail'),
    url(r'^manager/projects/details/(?P<slug>[\w-]+)', project_views.project_detail_view, name='project_detail'),
)

login/urls.py
from django.conf.urls import patterns, url

from login import views

urlpatterns = patterns('',
    url(r'^$', views.login_view, name='login'),
    url(r'^logout$', views.logout_view, name='logout'),
    #url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    #url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    #url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

tasks/urls.py
from django.conf.urls import patterns, url

from tasks import views

urlpatterns = patterns('',
    url(r'^details/(?P<slug>[\w-]+)', views.detail, name='detail'),
    url(r'^addTask/(?P<slug>[\w-]+)', views.add_project_task, name='add_task')
)

home/models.py
from django.db import models

# Create your models here.

home/views.py
# Create your views here.
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import logout_then_login
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.contrib import messages

from django.contrib.auth.models import User
from projects.models import Project
from tasks.models import Task


def user_profile_view(request):
    if request.user.is_authenticated():
        send_dict={}
        user = User.objects.get(username = request.user.username)
        task = Task.objects.filter(user= user)
        send_dict['task_list'] = task
        return render_to_response('users/home.html',send_dict,context_instance=RequestContext(request))
    else:
        return(redirect(reverse('Login:login')))


def manager_profile_view(request):
    if request.user.is_authenticated() and request.user.is_staff:
        send_dict={}
        user = User.objects.get(username = request.user.username)
        projects = Project.objects.filter(user= user)
        send_dict['projects'] = projects
        return render_to_response('managers/home.html',send_dict,context_instance=RequestContext(request))
    else:
        return(redirect(reverse('Login:login')))     

templates/managers/add_project.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Manager Dashboard</title>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<style>
body{
	font-family:Arial,Helvetica,sans-serif;
	font-size: 12px;
}
</style>

<script type="text/javascript">window.__admin_media_prefix__ = "/static/admin/";</script>

<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css"/>
<link rel="stylesheet" type="text/css" href="/static/admin/css/widgets.css"/>

{{ form.media }}




</head>
<body>
    <h1> New Project Dashboard </h1><br />
<!-- <h1> Add a new project </h1><br /> -->
<a href="{% url 'Home:manager' %}"> back  </a>||
<a href="{% url 'Login:logout' %}"> logout </a>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %} 
<form action= " {% url 'Home:add_project' %}" method="post">
            {% csrf_token %}
<table>
            {% for each_field in form %}   
                <tr>
                    <td>{{each_field.label}}</td>
                    <td>{{each_field}}</td>
                    <td>{{each_field.error}}</td>
                </tr>   
            {% endfor %}
</table>
<input type="submit" value="Submit Form">
             </form> 

</body>

</html>

templates/managers/home.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Manager Dashboard</title>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<style>
body{
	font-family:Arial,Helvetica,sans-serif;
	font-size: 12px;
}
</style>
</head>
<body>
<h1> Project Manager Dashboard </h1><br />
<a href="{% url 'Login:logout' %}"> logout </a>||<a href="{% url 'Home:add_project' %}"> Add projects </a>
<h3> Projects</h3>


<table border ="1" width ="40%">
    <thead><th>Name</th><th>description</th><th>start date</th><th>end date</th></thead>
            {% for each_project in projects %}   
                <tr>
                    <td><a href="{% url 'Home:project_detail' slug=each_project.slug %}">{{each_project.name}}</a></td>
                    <td>{{each_project.description}}</td>
                    <td>{{each_project.start_date}}</td>
                    <td>{{each_project.end_date}}</td>
                </tr>   
            {% endfor %}
</table>

</body>
</html>

templates/managers/project_detail.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Manager Dashboard</title>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<style>
body{
	font-family:Arial,Helvetica,sans-serif;
	font-size: 12px;
}
</style>
</head>
<body>
<h1> Project Details Dashboard </h1><br />
<a href="{% url 'Login:logout' %}"> logout </a>||<a href="{% url 'Home:manager' %}"> Back </a>||
<a href="{% url 'Task:add_task' slug=project.slug %}">Add Task</a>
<h3> {{ project.name }}</h3>

{% if task_list %}
	<table border ="1" width="50%">
    <tr>
        <th>Task Name</th>
        <th>Task description</th>
        <th>Start date</th>
        <th>End date</th>
        <th>User</th>
    </tr>
	{% for task in task_list %}
	<tr> 
        <td><a href= "{% url 'Task:detail' slug=task.slug %}">{{ task.name }}</a></td>
        <td>{{ task.description }}</td>
        <td>{{ task.start_date }}</td>
        <td>{{ task.end_date }}</td>
        <td>{{ task.user.username }}</td>
    </tr> 
	{% endfor %}
{% else %}
	<p>No taskss are available.</p>
{% endif %}
</body>
</html>